create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  type text not null check (type in ('fonte', 'bloco', 'grupo', 'acao')),
  parent_id bigint references public.categories(id) on delete set null,
  active boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists categories_parent_id_idx on public.categories(parent_id);
create index if not exists categories_type_idx on public.categories(type);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row
execute function public.set_updated_at();

create table if not exists public.expense_classifications (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists expense_classifications_code_unique
on public.expense_classifications(code)
where code is not null;

drop trigger if exists expense_classifications_set_updated_at on public.expense_classifications;
create trigger expense_classifications_set_updated_at
before update on public.expense_classifications
for each row
execute function public.set_updated_at();

create or replace function public.sync_revenue_ids()
returns trigger
language plpgsql
as $$
begin
  if new.source_id is null and new.fonte_id is not null then
    new.source_id := new.fonte_id;
  end if;

  if new.category_id is null and new.acao_id is not null then
    new.category_id := new.acao_id;
  end if;

  if new.fonte_id is null and new.source_id is not null then
    new.fonte_id := new.source_id;
  end if;

  if new.acao_id is null and new.category_id is not null then
    new.acao_id := new.category_id;
  end if;

  return new;
end;
$$;

create table if not exists public.revenues (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(15,2) not null,
  date date not null,

  source_id bigint references public.categories(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  type text,

  fonte_id bigint references public.categories(id) on delete set null,
  bloco_id bigint references public.categories(id) on delete set null,
  grupo_id bigint references public.categories(id) on delete set null,
  acao_id bigint references public.categories(id) on delete set null,

  observation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists revenues_date_idx on public.revenues(date);
create index if not exists revenues_source_id_idx on public.revenues(source_id);
create index if not exists revenues_category_id_idx on public.revenues(category_id);

drop trigger if exists revenues_set_updated_at on public.revenues;
create trigger revenues_set_updated_at
before update on public.revenues
for each row
execute function public.set_updated_at();

drop trigger if exists revenues_sync_ids on public.revenues;
create trigger revenues_sync_ids
before insert or update on public.revenues
for each row
execute function public.sync_revenue_ids();

create or replace function public.sync_expense_ids()
returns trigger
language plpgsql
as $$
begin
  if new.source_id is null and new.fonte_id is not null then
    new.source_id := new.fonte_id;
  end if;

  if new.category_id is null and new.acao_id is not null then
    new.category_id := new.acao_id;
  end if;

  if new.classification_id is null and new.expense_classification_id is not null then
    new.classification_id := new.expense_classification_id;
  end if;

  if new.fonte_id is null and new.source_id is not null then
    new.fonte_id := new.source_id;
  end if;

  if new.acao_id is null and new.category_id is not null then
    new.acao_id := new.category_id;
  end if;

  if new.expense_classification_id is null and new.classification_id is not null then
    new.expense_classification_id := new.classification_id;
  end if;

  return new;
end;
$$;

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(15,2) not null,
  date date not null,

  source_id bigint references public.categories(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  classification_id bigint references public.expense_classifications(id) on delete set null,
  type text,

  fonte_id bigint references public.categories(id) on delete set null,
  bloco_id bigint references public.categories(id) on delete set null,
  grupo_id bigint references public.categories(id) on delete set null,
  acao_id bigint references public.categories(id) on delete set null,
  expense_classification_id bigint references public.expense_classifications(id) on delete set null,

  observation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists expenses_date_idx on public.expenses(date);
create index if not exists expenses_source_id_idx on public.expenses(source_id);
create index if not exists expenses_category_id_idx on public.expenses(category_id);
create index if not exists expenses_classification_id_idx on public.expenses(classification_id);

drop trigger if exists expenses_set_updated_at on public.expenses;
create trigger expenses_set_updated_at
before update on public.expenses
for each row
execute function public.set_updated_at();

drop trigger if exists expenses_sync_ids on public.expenses;
create trigger expenses_sync_ids
before insert or update on public.expenses
for each row
execute function public.sync_expense_ids();

create table if not exists public.city_settings (
  id bigint generated by default as identity primary key,
  city_name text not null,
  city_hall_name text not null,
  address text not null,
  ibge_code text not null,
  state text not null,
  zip_code text,
  phone text,
  email text,
  mayor_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists city_settings_set_updated_at on public.city_settings;
create trigger city_settings_set_updated_at
before update on public.city_settings
for each row
execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.expense_classifications enable row level security;
alter table public.revenues enable row level security;
alter table public.expenses enable row level security;
alter table public.city_settings enable row level security;

drop policy if exists categories_select_auth on public.categories;
create policy categories_select_auth on public.categories
for select to authenticated
using (true);

drop policy if exists categories_insert_auth on public.categories;
create policy categories_insert_auth on public.categories
for insert to authenticated
with check (true);

drop policy if exists categories_update_auth on public.categories;
create policy categories_update_auth on public.categories
for update to authenticated
using (true)
with check (true);

drop policy if exists categories_delete_auth on public.categories;
create policy categories_delete_auth on public.categories
for delete to authenticated
using (true);

drop policy if exists expense_classifications_select_auth on public.expense_classifications;
create policy expense_classifications_select_auth on public.expense_classifications
for select to authenticated
using (true);

drop policy if exists expense_classifications_insert_auth on public.expense_classifications;
create policy expense_classifications_insert_auth on public.expense_classifications
for insert to authenticated
with check (true);

drop policy if exists expense_classifications_update_auth on public.expense_classifications;
create policy expense_classifications_update_auth on public.expense_classifications
for update to authenticated
using (true)
with check (true);

drop policy if exists expense_classifications_delete_auth on public.expense_classifications;
create policy expense_classifications_delete_auth on public.expense_classifications
for delete to authenticated
using (true);

drop policy if exists revenues_select_auth on public.revenues;
create policy revenues_select_auth on public.revenues
for select to authenticated
using (true);

drop policy if exists revenues_insert_auth on public.revenues;
create policy revenues_insert_auth on public.revenues
for insert to authenticated
with check (true);

drop policy if exists revenues_update_auth on public.revenues;
create policy revenues_update_auth on public.revenues
for update to authenticated
using (true)
with check (true);

drop policy if exists revenues_delete_auth on public.revenues;
create policy revenues_delete_auth on public.revenues
for delete to authenticated
using (true);

drop policy if exists expenses_select_auth on public.expenses;
create policy expenses_select_auth on public.expenses
for select to authenticated
using (true);

drop policy if exists expenses_insert_auth on public.expenses;
create policy expenses_insert_auth on public.expenses
for insert to authenticated
with check (true);

drop policy if exists expenses_update_auth on public.expenses;
create policy expenses_update_auth on public.expenses
for update to authenticated
using (true)
with check (true);

drop policy if exists expenses_delete_auth on public.expenses;
create policy expenses_delete_auth on public.expenses
for delete to authenticated
using (true);

drop policy if exists city_settings_select_auth on public.city_settings;
create policy city_settings_select_auth on public.city_settings
for select to authenticated
using (true);

drop policy if exists city_settings_insert_auth on public.city_settings;
create policy city_settings_insert_auth on public.city_settings
for insert to authenticated
with check (true);

drop policy if exists city_settings_update_auth on public.city_settings;
create policy city_settings_update_auth on public.city_settings
for update to authenticated
using (true)
with check (true);

drop policy if exists city_settings_delete_auth on public.city_settings;
create policy city_settings_delete_auth on public.city_settings
for delete to authenticated
using (true);

